language: php

php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

services:
  - mysql

env:
  global:
    - DB_HOST="127.0.0.1"
    - DB_NAME="illchuklock"
    - DB_USER="travis"
    - DB_PASS=""

before_script:
 - chmod +x test/install-apcu.sh
 - test/install-apcu.sh
 - phpenv config-add test/apc.ini
 - mysql -uroot -e "CREATE DATABASE $DB_NAME;" || aborterror "Unable to create database."
 - mysql -uroot $DB_NAME < data/illchuk_lock.sql || aborterror "Unable to import table."
 - mysql -uroot -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'$DB_HOST';"
 - composer install

notifications:
  email: false
